### ISSUE TITLE
app crashes on desktop safari

### ISSUE THREAD

**Issue by Syncretik** [Glo-Foundation/glo-wallet#125]
<img width="1840" alt="Screen Shot 2023-06-20 at 6 27 42 AM" src="https://github.com/Glo-Foundation/glo-wallet/assets/6061507/34562cf9-458e-435d-b06a-eb10afddd9a3">

<img width="1840" alt="Screen Shot 2023-06-20 at 6 36 59 AM" src="https://github.com/Glo-Foundation/glo-wallet/assets/6061507/e40d74b4-448d-4db2-8a7f-eef31516c77f">

**Comment by gglucass** [comment]
Already resolved? Seems to work well here, so closing. Please reopen and investigate if you are still experiencing this @Syncretik
