### ISSUE TITLE
Transactions UI is off

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#148]
Current:
<img width="450" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1226415/5bcf02e9-7f48-4ff8-aa62-07ff106df664">

Previously was:
<img width="454" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1226415/8c42cea5-8fb7-4628-8c1b-4b5e68c8fa77">

Let's make sure it returns to that

**Comment by Syncretik** [comment]
did you notice this before, looks like the styles haven't been touched in a couple weeks o.O
