### ISSUE TITLE
Log out & changing network should be in a dropdown menu

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#15]
This doesn't really look amazing yet
<img width="494" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1226415/634be963-dbc6-4b97-b8ef-4658ef3bf904">

1. Let's have a cyan circle with a 👤 in it
2. On hover / click show the wallet address modal
<img width="451" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1226415/10465c4c-d75e-41f9-822c-7c9b45313d76">
3. Add three buttons there: logout, Polygon & Ethereum.

**Comment by Syncretik** [comment]
fine we can eat hamburgers >:(

**Comment by Syncretik** [comment]
ah so chain-switching? for 2.?

**Comment by gglucass** [comment]
> ah so chain-switching? for 2.?

It's already there in the "Polygon Mumbai" button as done by @Riglanto . I'm ok with keeping it simple but UX definitely needs to be better than this :p

**Comment by Syncretik** [comment]
This is new to me as of waking up! :P

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Syncretik** [comment]
hmm there's an issue I'm running into right now, the wagmi disconnect hook doesn't fire when the log out button is embedded in the address modal, I'm guessing it's because the modal mounts independently of the root app and is missing context?
