### ISSUE TITLE
Buy Glo modal: dollar input UI broken

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#150]
Current:
<img width="493" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1226415/00ec8fbb-544d-4f99-bf6c-87493edf694f">

Previously was:
<img width="421" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1226415/cf239582-ac89-4441-9188-de8a265014a7">

Let's make sure it returns to that

**Comment by Syncretik** [comment]
The impact input should definitely have its own custom component styling since it's not shared anywhere else
