### ISSUE TITLE
Write component based styling guidelines for the project

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#151]
These guidelines will help prevent issues like: https://github.com/Glo-Foundation/glo-wallet/issues/150 and https://github.com/Glo-Foundation/glo-wallet/issues/148 from occurring in future

**Comment by Riglanto** [comment]
1. It makes sense to adjust globally used elements like h2 -> https://v1.tailwindcss.com/docs/adding-base-styles#using-css
2. However the whole idea of Tailwind is to keep class names with html elements for more optimal work. Hari suggested to keep style within components and it makes sense. The idea is simple, when you add a new component you can keep it in-line, if it's bigger (or reused) you can extract it at a top of file, if you want to use it in multiple files just export it to new .ts
3. Also if we want to keep styles in css, you wouldn't drop all styles / class names in same file. So keeping everything in global it's not going to work.
4. In any case, no matter where we keep styles - if the style is used in X components, and you adjust the style you need to double check all the components that are using the style. Alternatively you can override the style on the component level.
