### ISSUE TITLE
Add name, picture, twitter, email to profile

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#180]
Add basic profile info to your connected account, and then show it on the impact page

![Image](https://github.com/Glo-Foundation/glo-wallet/assets/1226415/97604fad-a4a6-4a7f-973a-c26b25cd53cd)

![Image](https://github.com/Glo-Foundation/glo-wallet/assets/1226415/6e970fba-f2e1-42db-8f2f-bba1f2667fa1)

**Comment by Riglanto** [comment]
1. Do you wanna fetch profile from connected acc with Sequence? 
![image](https://github.com/Glo-Foundation/glo-wallet/assets/6277878/448a5d0b-5f4a-4f0e-9bdc-de2abcab3ad4)
2. or Add profile editor? (that we store)
3. or Add connect profile button? :P

**Comment by gglucass** [comment]
@Riglanto profile editor please :-)

**Comment by gglucass** [comment]
Paused for now, but progress is in: https://github.com/Glo-Foundation/glo-wallet/tree/180-add-name-picture-twitter-email-to-profile
