### ISSUE TITLE
change order of Help Grow Glo CTAs

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#188]
1. Tweet your impact
2. Join as early adopter
3. Buy Glo merch

Let's remove "Share Glo with friends" for now.

**Comment by gglucass** [comment]
@Riglanto this hasn't been done afaict?

**Comment by Riglanto** [comment]
Seems like partially done :thinking:

**Comment by Riglanto** [comment]
https://github.com/Glo-Foundation/glo-wallet/pull/220
