### ISSUE TITLE
Add spinning Glo icon to impact animation on wallet connection

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#189]
Lottiefile coming soon

**Comment by gglucass** [comment]
@Syncretik apologies for the delay on this - here's the lottiefiles

[Cyan on pine lottiefiles.zip](https://github.com/Glo-Foundation/glo-wallet/files/12169508/Cyan.on.pine.lottiefiles.zip)

**Comment by Syncretik** [comment]
do we need this for launch?

**Comment by gglucass** [comment]
> do we need this for launch?

Yes please. This is the only flashy animation that people will see regardless of their Glo balance --> important for a great first experience. Let's discuss with broader team if someone needs to take over this ticket / another one that's on your plate.
