### ISSUE TITLE
Prepopulate user's email into the refer-a-friend and early-adopter flows

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#20]
Currently when I click the CTA to refer a friend I go into a form with empty values.

![image](https://github.com/Glo-Foundation/glo-wallet/assets/1226415/fc969b22-b7f6-4bc5-a6e3-c670efc89b0a)

<img width="1584" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1226415/fb91fe74-76af-48ac-b5df-f205badc234f">

In order to verify whether a user completed these flows, we need to match the email address in our database with the list of people that completed the refer-a-friend and early-adopter flows. 

To make sure that people enter the right email, let's prepopulate with the user's email address that we know as part of the email-based login flow

**Comment by Syncretik** [comment]
is there a way to get this cleanly through wagmi, if I'm assuming that is the way we interface with providers?
I read it was using Torus under the hood but it's unclear how to retrieve social login info, everything I've read is either web3 or saying to use Rainbow

**Comment by gglucass** [comment]
> is there a way to get this cleanly through wagmi, if I'm assuming that is the way we interface with providers? I read it was using Torus under the hood but it's unclear how to retrieve social login info, everything I've read is either web3 or saying to use Rainbow

TORUS is now replaced with Sequence. When logged in with Sequence you need to ask for email - see https://docs.google.com/spreadsheets/d/1oLHuq8at909K18eIdUgQwMO8jkqE8e5eHVbVKH1U5qk/edit?disco=AAAAyLDgwsE&usp=comment_email_discussion&ts=647d8321&usp_dm=false

**Comment by Syncretik** [comment]
hm while that param work (getting prompt for email check on connect), Sequence relies on retrieving that email through a returned `connectDetails` which I'm sure is provided by wagmi (wagmi `connect` func from `isConnected` hook returns nothing)

**Comment by gglucass** [comment]
> hm while that param works (getting prompt for email check on connect), Sequence relies on retrieving that email through a returned `connectDetails` which I'm pretty sure is not provided by wagmi (wagmi `connect` func from `isConnected` hook returns nothing)

wagmi doesn't have `connectDetails` afaik; think it's just naming coincidence?

**Comment by Syncretik** [comment]
no but that's where the email info is coming back from is what I'm saying. a successful connection with sequence will return a `connectDetails` object but wagmi doesn't.

at least, I don't see it here:
https://docs.sequence.xyz/wallet/connectors/wagmi/

**Comment by Syncretik** [comment]
@gglucass this is going to be more effort than it's worth. by siloing Sequence out by itself we also lose all the lifecycle connectors that wagmi conveniently provides, which means I'll have to duplicate a lot of state logic to make sure checks and data fetches propagate appropriately :/

**Comment by gglucass** [comment]
> @gglucass this is going to be more effort than it's worth. by siloing Sequence out by itself we also lose all the lifecycle connectors that wagmi conveniently provides, which means I'll have to duplicate a lot of state logic to make sure checks and data fetches propagate appropriately :/

This is a must have requirement, so we're going to need to find some way to make it work. Let's discuss in depth later today / tomorrow (depending on how well the smart contracts upgrading goes)

**Comment by gglucass** [comment]
https://glodollar.slack.com/archives/C03CD2VKP2M/p1686039777427689?thread_ts=1686034097.323049&cid=C03CD2VKP2M this maybe good news @Syncretik :-)

<img width="376" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1226415/11633849-2ec3-46de-bb70-f0239c5518af">
