### ISSUE TITLE
Buy Glo flow: coinbase click-through shouldn't open coinbase page

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#202]
When I click the "Coinbase" option here:
<img width="552" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1226415/860fc086-f777-4353-b560-2caf5006a1b2">

It opens a link to coinbase.com - this shouldn't happen.

**Comment by Riglanto** [comment]
@gglucass what should it open?

**Comment by gglucass** [comment]
> @gglucass what should it open?

Nothing. It should only show the multistep instructions in the modal.

**Comment by Riglanto** [comment]
I guess this is the thing @Syncretik is connecting, right?

**Comment by Syncretik** [comment]
yup I didn't touch the opening of the coinbase modal because I wasn't sure if that was expected behaviour
