### ISSUE TITLE
Buy Glo flow: check for USDC balance before clicking through

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#203]
My wallet already has 1000 USDC, yet the todo item here isn't checked off already. Only when I click through to Coinbase does it turn green. Let's make sure to check the USDC balance on load of this component too.

<img width="448" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1226415/b7187e01-3487-4d2c-95d2-3f4b6700dc5c">

**Comment by Syncretik** [comment]
I think this should be resolved with #209?

**Comment by gglucass** [comment]
> I think this should be resolved with #209?

Just tried it - doesn't look like it.

**Comment by Syncretik** [comment]
on mainnet? I didn't include testnet support. it should be checking as soon as the balance gets fetched on mount

**Comment by gglucass** [comment]
> on mainnet? I didn't include testnet support. it should be checking as soon as the balance gets fetched on mount

connected on mainnet, using testnet.glodollar.org

**Comment by gglucass** [comment]
@Syncretik seems my USDC balance isn't being detected at all anymore on testnet.glodollar.org atm

**Comment by Syncretik** [comment]
well that makes sense because we didn't include testnet support (ref ^) it was part of the PR
