### ISSUE TITLE
Buy Glo flow: inconsistent window opening style

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#205]
Steps 1-3 open in a new tab, whilst the "Buy $1000 on Uniswap" button opens in a small new window. Can we make sure this is consistent between all buttons? Newtab best imo.

**Comment by Syncretik** [comment]
this is linked to the payment options utilities, should we open all those in a new tab as well?

**Comment by Syncretik** [comment]
this ties in with #207 as well -- @Riglanto do we _need_ the named context for the second param in `window.open` in the helpers? one other caveat of opening in a new window is that it might not render if user has certain popup blocker extensions enabled

**Comment by gglucass** [comment]
> this is linked to the payment options utilities, should we open all those in a new tab as well?

I am good with doing everything in newtab yes.

@Riglanto can you chime in on above?

**Comment by Riglanto** [comment]
The new window story started with Twitter - it made a lot of sense to use it there. (so the user does not lose context, and tabs lol)

For payment I don't have strong opinion if it should be new window or new tab. Looking at your discussion let's just go with new tabs.

Sidenote: I don't think the context name matter for `window.open` @Syncretik
