### ISSUE TITLE
Buy Glo flow - ratio broken

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#206]
When using metamask and I click on Ratio then the app breaks

<img width="751" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1226415/cb772c74-313c-452d-b25e-c483603ded6d">

**Comment by Syncretik** [comment]
I noticed this as well last week

**Comment by Riglanto** [comment]
What env, what error :roll_eyes:  ?

At least we miss Ratio prod access. Did we get non-sandbox credentials from them? @gglucass

**Comment by gglucass** [comment]
> What env, what error 🙄 ?
> 
> At least we miss Ratio prod access. Did we get non-sandbox credentials from them? @gglucass

This was on testnet.glodollar.org with mac os x, no error. Still occurs for me.
