### ISSUE TITLE
"View all transactions" shows underneath the help grow glo component

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#211]
When the transactions are collapsed, they render as follows on Chrome Mac

<img width="434" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1226415/a1146894-f38e-4115-90bc-8e054039d0a8">

**Comment by gglucass** [comment]
This is still happening on both testnet.glodollar.org and the deployment branch in the linked PR @Syncretik

**Comment by Syncretik** [comment]
ah...that's because I forgot to push those changes up 🤒
