### ISSUE TITLE
Add opengraph and social images to app.glodollar.org

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#215]
So our links show a preview on social media - inspired by https://glodollar.slack.com/archives/C04JUM7D5JQ/p1690305984890849

For now let's add

![image](https://github.com/Glo-Foundation/glo-wallet/assets/1226415/1f979dd2-dee6-423c-a92d-95303e24b752)

**Comment by har777** [comment]
Closed via https://github.com/Glo-Foundation/glo-wallet/pull/231
