### ISSUE TITLE
Add an admin panel

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#221]
So that people can view data - consider the following options:

https://www.forestadmin.com/
https://dashibase.com/
https://budibase.com/

**Comment by Ectsang** [comment]
<img width="509" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1057844/c6ce8247-f023-4a01-94c5-86a12f1f8551">

@gglucass FYI automation is available

**Comment by Ectsang** [comment]
https://glo.budibase.app/app/users#/home

`marketing@glodollar.org` is invited as a basic user, which has read-only access to the User table.

@gglucass

**Comment by Ectsang** [comment]
Looks like this:
<img width="1820" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1057844/af8457c0-f919-4240-a100-2b3dcd1d4200">
