### ISSUE TITLE
Provide more context on the App Home Page

### ISSUE THREAD

**Issue by mblacken** [Glo-Foundation/glo-wallet#241]
It's not clear what people are signing up for when they land on app.glodollar.org or that they are creating a wallet when they select two of the four options.

Include text that says:

The Glo App is designed to be your one-stop shop for all things Glo Dollar. You can link an existing wallet or create a new one via Sequence.xyz and see the impact you're making just by holding Glo Dollar. The Glo app was built for everyone, from web3 natives to people just getting started with crypto.

Create a wallet via Sequence.xyz:
1. Email 
2. Social

OR 

Connect an existing wallet:
1. MetaMask
2. WalletConnect

**Comment by gglucass** [comment]
@mblacken thanks for your input. The proposed textual copy won't work with the current constraints and  what the user journeys look like on mobile: https://www.figma.com/file/396p2PzjnIXSbHmuBuj7oK/Website?type=design&node-id=4387%3A6030&mode=design&t=CCbWzPUhxKYJ2Bce-1  
1. This needs to be mobile friendly. This means we have about 10 words to work with at max.
2. People end up on app.glodollar.org in a variety of ways: our website, twitter, a shared impact page, email we push to our community. The UI needs to work for every source, and for every type of user. Presenting a non-crypto person with `Create a wallet via Sequence.xyz:` will not work - the terminology _needs_ to be something aligned with web 2.0 and result in a directive flow. This has been broadly agreed upon with marketing weeks ago.
3. In most places we will link to app.glodollar.org/buy which will immediately open the Buy Glo window upon sign up, as such people will not get lost regardless of the authentication method they use.

**Comment by gglucass** [comment]
@mblacken @setgree this is about the best I can do

<img width="436" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1226415/7249d97a-fb53-4403-b8d1-8de53f15c1f2">
