### ISSUE TITLE
Check impact of any address without any login

### ISSUE THREAD

**Issue by har777** [Glo-Foundation/glo-wallet#26]
Should be as simple as how etherscan does it: https://etherscan.io/address/address-hash

**Comment by gglucass** [comment]
+1 let's do it! Do you want to pick up @har777 ?

**Comment by har777** [comment]
@gglucass is there a finished design for this?

**Comment by gglucass** [comment]
> @gglucass is there a finished design for this?

No - let's just start by displaying it in exactly the same was as a logged in user would. We'll work on design after first few users have used it :-)
