### ISSUE TITLE
Email is not fetched on first Sequence login

### ISSUE THREAD

**Issue by Riglanto** [Glo-Foundation/glo-wallet#295]
If user is not logged in Sequence, the `askForEmail: true` param is ignored and we don't collect the email until the user reconnects.

On new login the popup with email info collection is presented:
![image](https://github.com/Glo-Foundation/glo-wallet/assets/6277878/856c3c55-e2cd-438e-8fa8-67ef37b66635)

**Comment by gglucass** [comment]
@Riglanto this is fixed now so closing
