### ISSUE TITLE
No 'scan' button if you go through walletConnect -> Sequence 

### ISSUE THREAD

**Issue by setgree** [Glo-Foundation/glo-wallet#322]
instead of social log in, go through WalletConnect, and either click 'Sequence' or search for Sequence, and then, no scan button on top level of Glo App

<img width="411" alt="Screenshot 2023-08-03 at 1 42 36 PM" src="https://github.com/Glo-Foundation/glo-wallet/assets/9850322/64e5de61-6012-433c-9536-2d272b17a92f">

**Comment by gglucass** [comment]
Thanks for reporting @setgree ! Unfortunately, however, this is intentional and a side-effect of how walletconnect works. This cannot be changed.
