### ISSUE TITLE
Add USDC balance to root screen

### ISSUE THREAD

**Issue by Syncretik** [Glo-Foundation/glo-wallet#329]
tentative design
![image](https://github.com/Glo-Foundation/glo-wallet/assets/6061507/2e7824b1-ee7f-4f2a-8310-213ac7617b87)

might put it on top with Balance: header

on click if Sequence open up buy guide
![image](https://github.com/Glo-Foundation/glo-wallet/assets/6061507/32acc102-f369-4472-81ad-fd0ee35330ca)

if metamask directly open uniswap link

**Comment by Syncretik** [comment]
@gglucass did we get feedback from konrad about this yet?

**Comment by gglucass** [comment]
> @gglucass did we get feedback from konrad about this yet?

Not yet. Let's just put it in text beneath the balance for the first fix. We'll get a nicer designed version that takes into account the stripping of the buttons & transactions early next week.

**Comment by Syncretik** [comment]
is the balance clickable? where does it redirect to, sequence.app deeplink?

**Comment by gglucass** [comment]
> is the balance clickable? where does it redirect to, sequence.app deeplink?

Let's deeplink into one of the following options:
1. the Coinbase + Uniswap buy guide, as that one provides instructions on how to swap USDC for USDGLO
2. Uniswap pair with USDC <> USDGLO

I'm a bit on the fence which one would be best, what do you think?

**Comment by Syncretik** [comment]
hm, I'd say the buy guide
you'll have some nice little validation with partial completion of everything but the last step :P

**Comment by gglucass** [comment]
@Syncretik let's go with buy guide then :-)!
