### ISSUE TITLE
Make the app network agnostic

### ISSUE THREAD

**Issue by har777** [Glo-Foundation/glo-wallet#331]
There is no reason to ask users to select and switch networks. The app should just fetch data from all supported networks + show an aggregated view. We can add a network selection dropdown during the "buy glo" workflow.

**Comment by gglucass** [comment]
@har777 proposed design:
<img width="360" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1226415/8cbbce89-68fe-48b9-9e51-b87e8c2f282f">

https://www.figma.com/file/396p2PzjnIXSbHmuBuj7oK/Website?type=design&node-id=4524%3A7661&mode=design&t=QVEw2YlcVtITS4A0-1

**Comment by Ectsang** [comment]
@gglucass would `Transactions` be displayed differently here (or would we assume users know these Transactions are on their current connected chain)? 

<img width="406" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1057844/b4a37a08-39b5-42cb-9fad-8ca617d4b9eb">

**Comment by gglucass** [comment]
@Ectsang like I mentioned on Slack we'll strip away the transactions component, so we can leave this design as is for now. https://github.com/Glo-Foundation/glo-wallet/issues/349
