### ISSUE TITLE
Replace Uniswap with Zeroswap when a user is signed in with Sequence

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#342]
https://glodollar.slack.com/archives/C04PNCYTT89/p1691509154052349

**Comment by Syncretik** [comment]
I can take this since I'm already updating Metamask to use internal marketplace + matcha?

**Comment by gglucass** [comment]
@Syncretik I added wip because I don't think it's ready to be picked up yet.
