### ISSUE TITLE
Add button to auto-distribute recipient splits

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#429]
When I add a new recipient, it auto splits the distribution %s equally among all the recipients you selected.
<img width="411" alt="image" src="https://github.com/user-attachments/assets/65e0beef-6ace-4a25-bbf0-c6f0e403c878">
<img width="486" alt="image" src="https://github.com/user-attachments/assets/be6fa6de-d2b1-4723-b4e0-5cbcbe7ab7bf">

When I then make a change to the distribution for one recipient, I need to manually readjust the numbers to be exactly 100%.
<img width="485" alt="image" src="https://github.com/user-attachments/assets/71b59b7f-c4dc-4236-9f64-72c6f6469c89">

Can we add a button to auto-distribute equally across the recipients that the user didn't touch?

**Comment by gglucass** [comment]
> Hi , i have got a couple of ideas on how best to solve this . COuld i be assigned this issue ??

Assigned. Please deliver upon this or the other ticket before requesting another assignment.

**Comment by gabrieltemtsen** [comment]
Does this fix the issue ? @gglucass 

https://github.com/user-attachments/assets/a1b8db66-9043-4a90-a4f9-526a4e611c30

**Comment by gglucass** [comment]
> Does this fix the issue ? @gglucass
> 
>  Screen.Recording.2024-10-15.at.13.38.39.mov

Hey @gabrieltemtsen - this looks pretty good. Instead of the auto-distribute button, can we change it so the auto-distribute is called when the user first presses save? Then show some visual feedback that it's been auto-distributed and that the user needs to press save again. Then on second click it prompts the signing interaction.

**Comment by gabrieltemtsen** [comment]
Thanks @gglucass let me try that now

when a user removes a recipient, the user still has to click on the auto distribute to get all the allocation to be a 100%

**Comment by gglucass** [comment]
> Thanks @gglucass let me try that now
> 
> when a user removes a recipient, the user still has to click on the auto distribute to get all the allocation to be a 100%

When a user removes a recipient the same flow can apply as I describe above imo. I _strongly_ prefer not to introduce an extra button.

**Comment by gabrieltemtsen** [comment]
> > Thanks @gglucass let me try that now
> > when a user removes a recipient, the user still has to click on the auto distribute to get all the allocation to be a 100%
> 
> When a user removes a recipient the same flow can apply as I describe above imo. I _strongly_ prefer not to introduce an extra button.

what do you think ? 

https://github.com/user-attachments/assets/324258a2-25ba-4ae2-a182-b30e1434c016

**Comment by gglucass** [comment]
> > > Thanks @gglucass let me try that now
> > > when a user removes a recipient, the user still has to click on the auto distribute to get all the allocation to be a 100%
> > 
> > 
> > When a user removes a recipient the same flow can apply as I describe above imo. I _strongly_ prefer not to introduce an extra button.
> 
> what do you think ?
> 
>  demoTest.mov

This looks good. Feel free to raise a PR
