### ISSUE TITLE
Remove the squiggle everywhere in UI

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#431]
![image](https://github.com/user-attachments/assets/9b55fe05-4050-49b8-a5bb-d1d347b0f638)

**Comment by gabrieltemtsen** [comment]
@gglucass please can I have a .env.example? seems it is missing in the repo

**Comment by gabrieltemtsen** [comment]
please assign this to me

**Comment by gabrieltemtsen** [comment]
https://github.com/Glo-Foundation/glo-wallet/pull/436
