### ISSUE TITLE
Replace logo in top left

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#434]
Please use this one. Wordmark no longer necessary.

![Glo Dollar Logo](https://github.com/user-attachments/assets/a1d491d4-7fcd-45f8-ad49-b690f85961e5)

**Comment by gabrieltemtsen** [comment]
@gglucass please can you assign this to me ?

**Comment by gabrieltemtsen** [comment]
@gglucass there was an error i got when I ran the project at first:
<img width="898" alt="image" src="https://github.com/user-attachments/assets/a0c4249e-d4fe-405f-b375-0fa01fbbace8">

So I added a line of code in https://github.com/Glo-Foundation/glo-wallet/blob/c5da86760364290238d6025ed1217fb0649384d2/pages/_app.tsx#L30  
just incase it doesn't get any rpc url from the list of chains

<img width="774" alt="image" src="https://github.com/user-attachments/assets/915ea548-cff2-4eb4-9f32-ff4f63bdc307">

**Comment by gglucass** [comment]
Thank you @gabrieltemtsen
