### ISSUE TITLE
UI feedback

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#5]
1. text / icons seem a bit unaligned vertically?
<img width="421" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1226415/dc0603dc-9c4e-4ad4-a411-a51ecdf6c0ec">

2. Description text in the Let's Glo action item's section is too large and not right color gray
<img width="405" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1226415/eb3f422f-3ee2-4385-ac89-e23593077af8">

3. Transactions & Let's Glo item's containers should be entirely clickable - now only the `v` and `>` is
<img width="499" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1226415/f5cb38ea-b12b-467a-acc0-860bda174923">

4. Balance should be formatted as a currency. So $ in front, decimal separators & 2 decimals shown always
<img width="472" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1226415/ded326ca-9598-42de-83c3-a1572c5f33f5">

5. Can we change "Connect" to "Log in"? And "Disconnect" to "Log out"? In majority of cases people with auth with google most likely
<img width="553" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1226415/e3563292-d5c0-4e46-a8b7-fcc383677a6f">

6. Transactions UI does not look like the [design](https://www.figma.com/file/396p2PzjnIXSbHmuBuj7oK/Website?type=design&node-id=3305%3A6023&t=Wr3G2uan545lgc8J-1)
<img width="443" alt="image" src="https://github.com/Glo-Foundation/glo-wallet/assets/1226415/f2150a41-a3c3-473f-b2e2-297d42800d00">

**Comment by Syncretik** [comment]
1. can do but it'll be annoying
2. that's actually the correct hex, it just looks diff from figma -> screen not sure why, maybe i'm missing something?
3. oh that's a good point will be more mobile friendly

**Comment by gglucass** [comment]
1. annoying but worth it imo @Syncretik !
2. as discussed on Slack it should be the _description text_ so "Glo is meant to be spent." etcetera that gets pine-700
3. Yay fixed!

**Comment by gglucass** [comment]
@Syncretik I edited the OP with two additional asks
