### ISSUE TITLE
Flashy impact animation when you open the wallet showing your impact

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#56]
Click on Prototype and press the play button to see the animation

https://www.figma.com/file/396p2PzjnIXSbHmuBuj7oK/Website?type=design&node-id=2986%3A6132&t=Zv54ThT39Ya7w6br-1

**Comment by Syncretik** [comment]
resovled with #48

**Comment by gglucass** [comment]
@Syncretik with this I meant the sexy animation that rolls the Glo logo in the screen when you login 👀

**Comment by Syncretik** [comment]
yup misread my mistake

**Comment by Syncretik** [comment]
@gglucass feedback on prototype 1:
- I think having a constant rotation of the logo is distracting, maybe only one revolution after the transitional movements? feels out of place when the rest of the page is static, esp with a bezier-type rotation
- should the logo in top-left do the same style of rotation on hover?

**Comment by gglucass** [comment]
> @gglucass feedback on prototype 1:
> 
> * I think having a constant rotation of the logo is distracting, maybe only one revolution after the transitional movements? feels out of place when the rest of the page is static, esp with a bezier-type rotation
> * should the logo in top-left do the same style of rotation on hover?

1. I agree having a single rotation is sufficient
2. Hah, I like it! If that's easy to add then yes by all means :-)
