### ISSUE TITLE
Mobile styles of login modal

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#89]
![IMG_2524](https://github.com/Glo-Foundation/glo-wallet/assets/1226415/12dfa912-e0a4-453b-b25a-4e30078e22a7)

- [ ] Jeff's head is cut off
- [x] Social login should be on one line
- [x] Scrolling doesn't work

**Comment by Syncretik** [comment]
@gglucass can you add dimensions that you're starting to notice this?

**Comment by gglucass** [comment]
> @gglucass can you add dimensions that you're starting to notice this?

iPhone 13 mini dimensions - 375px × 812px

**Comment by Syncretik** [comment]
ok this tracks makes sense it's a mini phone, current gens are ok. will add media queries :)

**Comment by Syncretik** [comment]
@gglucass do we want to re-introduce the original styling that was reverted in #90? it is _fixed_ but imo it definitely is missing a level of flair now

<img width="827" alt="Screen Shot 2023-06-14 at 4 09 48 AM" src="https://github.com/Glo-Foundation/glo-wallet/assets/6061507/8c222b16-b879-4bc7-a40f-34484a67e1f4">
