### ISSUE TITLE
Stay connected on refresh

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#9]
When I am connected to the Glo Wallet with my metamask wallet
And I refresh the page
Then I am no longer connected

Is it possible to maintain that connection?

**Comment by Riglanto** [comment]
I added "reconnect" recently, but haven't found "keep connect" option

**Comment by gglucass** [comment]
I think reconnect is fine! But probably we want to have some checks before we run reconnect similar to how uniswap only instantiates it in specific contexts?

**Comment by Riglanto** [comment]
I asked Hari to look at that as I'm out of the ideas.

**Comment by gglucass** [comment]
@Riglanto @har777 looking into this I think the trick is just to _not_ call reconnect and simply rely on wagmi's built in connectivity features. At least when I remove the reconnect logic now I _do_ stay connected to the app...!
