### ISSUE TITLE
Mobile styles buy Glo modal

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#90]
![IMG_2525](https://github.com/Glo-Foundation/glo-wallet/assets/1226415/51ff7f5b-f5fa-4690-a4a8-66f90ae69035)

- [ ] Input is invisible
- [ ] Cannot get to the buy glo button, scroll doesn't work?
- [ ] Two x's at the top

**Comment by har777** [comment]
@Syncretik i think you accidentally merged the common modal close button(the x) back. We cant have it as a common row for all modals because a lot of designs require the close button inline with the actual modal contents.

**Comment by har777** [comment]
Looks like all these issues are from some bad merge.

**Comment by Syncretik** [comment]
ah ok I took out the commented code cuz I thought someone was just testing it, comments would be helpful next time
