### ISSUE TITLE
Copied animation on click of wallet address has disappeared

### ISSUE THREAD

**Issue by gglucass** [Glo-Foundation/glo-wallet#99]
When I click on the wallet address I expect a copied tooltip to animate. It was there and now it's not. 
Was it removed in a merge?

**Comment by Syncretik** [comment]
[it's still here in dev 🤔](https://www.loom.com/share/e97ee2ab8cf542b58ccd3fabacec88d1?sid=85570130-27ba-444b-ac4e-85e5681e14d5)

**Comment by gglucass** [comment]
@Ectsang maybe good one to get in the groove of things again :D?
